#ifndef ZKGPU_FFI_H
#define ZKGPU_FFI_H

/* This file is auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define FFI_API_VERSION 1

/**
 * Run a harness request encoded as UTF-8 JSON and return a newly allocated
 * UTF-8 JSON response string.
 *
 * # Safety
 *
 * `request_json` must be either null or a valid, NUL-terminated C string
 * pointer that remains alive for the duration of the call. The returned
 * pointer must be released exactly once with [`zkgpu_free_string`].
 */
char *zkgpu_run_request_json(const char *request_json);

char *zkgpu_get_version_json(void);

/**
 * Free a string previously returned by [`zkgpu_run_request_json`] or
 * [`zkgpu_get_version_json`].
 *
 * # Safety
 *
 * `ptr` must be either null or a pointer returned by this library via
 * `CString::into_raw`. Passing any other pointer, or freeing the same pointer
 * more than once, is undefined behavior.
 */
void zkgpu_free_string(char *ptr);

#endif  /* ZKGPU_FFI_H */
